[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors *"
    X-Frame-Options = "ALLOWALL" #deprecated but best option
    Content-Encoding = "identity"

[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
